spring:
  application:
    name: oauth2 #추가
  datasource:
    #url: jdbc:mysql://localhost:3306/study
    #로컬 사용시
    url: ${DB_URL}
    #RDS 사용시 - 인텔리제이 환경변수 설정
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update #create
          #auto: create는 기존 테이블을 모두 없애버리고 새로 만들게 됨
          #JPA가 @Entity가 붙은 대상을 찾아내어 Database에 테이블을 만들게 됨
          #auto: update는 바뀐 부분에 대해서만 적용을 해줌
          #처음 Database를 만드는 것 아니라면 update로 해두는 것이 좋음
        default_batch_fetch_size: 1000

#아래 추가
logging:
   level:
    root: info
    com.psc.sample: debug
server:
  port:80
